name: Continue workflow and job execution
on:
  push:
    branches:
      - dev
    paths:
      - 'starting-basic-action/**'
      - '.github/workflows/continue-jobs-execution-flow.yml'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starting-basic-action
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: starting-basic-action/node_modules
          key: ${{ runner.os }}-deps-node-modules-${{ hashFiles('starting-basic-action/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starting-basic-action
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: starting-basic-action/node_modules
          key: ${{ runner.os }}-deps-node-modules-${{ hashFiles('starting-basic-action/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        continue-on-error: true
        id: run-tests
        run: npm run test
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: starting-basic-action/test.json
  build:
    needs: [lint , test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starting-basic-action
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: starting-basic-action/node_modules
          key: ${{ runner.os }}-deps-node-modules-${{ hashFiles('starting-basic-action/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: starting-basic-action/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: starting-basic-action/dist
      - name: Output contents
        run: ls -R starting-basic-action/dist
      - name: Deploy
        run: echo "Deploying..."
  report:
    needs: [lint ,test , build, deploy]
    if: always() && contains(needs.*.result, 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo "${{ toJSON(github) }}"

