name: Matrix Demo
on:
  push:
    paths:
    - 'starting-basic-action/**'
    - '.github/workflows/**'

jobs:
  build:
    strategy:
      fail-fast: false # <--- Impedisce la cancellazione degli altri job
      matrix:
        node-version: [ 20 , 23, 24 ]
        operating-system: [ubuntu-latest , windows-latest]
        include:
            - node-version: 22
              operating-system: ubuntu-latest
        exclude:
            - node-version: 20
              operating-system: windows-latest
    runs-on: ${{ matrix.operating-system}}
    defaults:
      run:
        working-directory: ./starting-basic-action # <--- Assicurati che sia corretta
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node Js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build



